### ISSUE TITLE
Rather cryptic VSCoreDebugProtocol.ProtocolException when running example code

### ISSUE THREAD

**Issue by zutron** [NVentimiglia/Blazor.Transitions#1]
Hi there,

Very interested to get this working on my .NET 5.0 Blazor web assembly project but after implementing it doesnt work as expected. Everything compiles fine, I don't get any runtime errors, but I just have no animations.

When trying to run your example project I just get a VSCoreDebugProtocol.ProtocolException and the code refuses to run. I've not had much luck tracing the cause of the problem.

Are you using this code in production? Have you tried it against .NET 5?

I originally used the Blazor.Animate library, but that one doesn't have the ability to programmatically hide/fade animations, only show/fadein. 

Thanks

**Comment by NVentimiglia** [comment]
Have not updated the project since inception. Not currently developing with blazor. I am happy to accept a pr or answer any questions.

**Comment by zutron** [comment]
Managed to get everything working smoothly with a fresh project under .net 5. PR issued if you want to update your example :thumbsup:

**Comment by NVentimiglia** [comment]
awesome !
